d = {
    0: {
        'is_hired_1mo': {
            'best_pytorch': 1,
            'best_quantized': 0},
        'lost_job_1mo': {
            'best_pytorch': 1,
            'best_quantized': 0},
        'job_search': {
            'best_pytorch': 1,
            'best_quantized': 0}},
    1: {
        'is_hired_1mo': {
            'best_pytorch': 1,
            'best_quantized': 0},
        'lost_job_1mo': {
            'best_pytorch': 1,
            'best_quantized': 0},
        'job_search': {
            'best_pytorch': 1,
            'best_quantized': 0}}}
